### ISSUE TITLE
Communcate to A1800

### ISSUE THREAD

**Issue by maufc** [ElsterSolutionsOpensource/C12Adapter#3]
I am trying to communicate to A1800 meter.
Would this library suitable to do that?
Is there any guide or manual to do that?
Thanks!

**Comment by ElsterSolutionsOpensource** [comment]
Yes, you can use this library with the A1800 meter. For optical port communications, you need to use the ANSI C12.18 protocol ([https://elstersolutionsopensource.github.io/C12Adapter/class_m_protocol_c1218.html]) with either the Optical Probe channel (https://elstersolutionsopensource.github.io/C12Adapter/class_m_channel_optical_probe.html) or the Serial channel (https://elstersolutionsopensource.github.io/C12Adapter/class_m_channel_serial_port.html). The example for C12.22  communications (https://github.com/ElsterSolutionsOpensource/C12Adapter/tree/master/examples/cpp/c1222) can give you a starting point on how to create the communications objects. It reads ST_001 which the A1800 has. You will need to know what the data structures are in the A1800 meter, and for that you can look at the ANSI C12.19 standard.

**Comment by maufc** [comment]
Hi Nicole
Thanks so much for your answer. 
I'll be wondering if I can get the instantaneous values of the main variables. 
In the metercat software,  those are the instrumental values, it is an specific tab. 
I can guess there is a table defined in C12.19 I can send a request for and get that values.
I have optical, serial and even tcp option for send the request.
What about the validation process?
What do you mean for ST_001?
Best regards

**Comment by maufc** [comment]
Hi again. 
I just checked the C12.22 sample and it looks very straight forward.
I may try that example. 
Any tip for connect to the A1800?
I saw there some reference to ST_001 is that a info table of the meter?
Thanks again!

**Comment by ElsterSolutionsOpensource** [comment]
I can’t advise on data structures, other than to point you to the ANSI 12.19 standard. ST_001 (as I called it) is defined in the ANSI C12.19 standard as ‘Table 01 General Manufacturer Identification Table’. From that table, one can get the manufacturer, model, hardware/firmware version, and serial number. You can see it’s structure in the C12.22 example.

To use the The C12Adapter open source library, you need to create the communication object, and set any channel or protocol properties specific to the meter. For example, on a socket channel the Peer Address and Port needs to be set, on the Serial and Optical channels, the Port Name needs to be set. For the protocols, the security modes and keys/passwords need to be provided. When the protocols are paired with the Optical Probe channel, they control the baud rate through the Session Baud property, otherwise the Baud rate needs to be set on the Serial channel. There are other properties that control retries, timeouts, etc, but the default values provided by the library work well in most cases.

**Comment by maufc** [comment]
Thanks you again Nicole!
Your info is very useful for me.
In coming days, I'll make a try.
Definitely I have to check the table structures on C12.19
Quite a protocol.
Hope I can get the data I need.
Best regards

**Comment by maufc** [comment]
Hi Nicole. It's been some busy days to make any try.
I am pretty sure that I will be able to communicate via optical and serial ways.
Nevertheless, as I can see on Metercat software that you can use pure tcp/ip or tcp/ip C12.22.
Could you explain to me the difference between that two ways to use tcp/ip?
I can presume, but my doubt is if I can use the library (I mean the c12.22 example) directly to connect via pure tcp/ip as that is the way I use to connect to meters via a LTE modem.
Regards!

**Comment by ElsterSolutionsOpensource** [comment]
Hi Mauricio. In this case, you most likely want to pair the Socket channel with the ANSI C12.21 protocol. Once you have the channel and protocol properties setup correctly, you should be able to communicate to your meter with this library. Regards, Nicole.

**Comment by maufc** [comment]
Hi again
I understand that C12.21 is the way to use C12.18 through a modem and C12.22 the way to communicate via TCP/IP. Nevertheless, the modem insists that it is transparent communication and it got an IP and a Port where the metercat software makes the queries, but metercat algo got a TCP/IP C12.22 option to communicate. Is 'only' TCP/IP a hybrid kind of communication between serial and C12.22?
How would I be able to communicate to the meter with the library in this way? Socket channel is an option of the library. 
Thanks a lot!
Regards!!

**Comment by maufc** [comment]
It is a way to communicate,  right?
According to this configuration file:
https://github.com/ElsterSolutionsOpensource/C12Adapter/blob/master/examples/cpp/Reader/default.ini

**Comment by maufc** [comment]
Hi. Me again.
I just tried the with optical  probe and got an answer!
ST01 and ST02 easiest request are well answer following the repo: https://github.com/epri-dev/c12test based on this library. Never the less, when I ask for tables, I got the following answer for mostly all the relevant tables:
### Error: 0x03 Insufficient Security Clearance (ISC) in TableRead(ST3[0x0003])
Is there an additional security validation not covered by the library or is it a matter of protected information?
The meter is new, coming with factory settings... even more, I programmed from scratch with metercat. 
Password profile in metercat are the factory default.
Any clue or suggestion?
Thanks!

**Comment by ElsterSolutionsOpensource** [comment]
Hi Mauricio,

Sounds like you are making great progress!

First, just a gentle reminder that I don’t need to know passwords, and those should never be revealed :)

In regards to your question about TCP/IP and ANSI C12.21, the answer is they can be used together. The C12Adapter library allows using any of its channels with any of its protocols. While generally it is correct to say that ANSI C12.21 is intended for Modems, it can and is also used with TCP/IP sockets. 

In regards to your question about the ISC error, make sure that you have enabled sending the security service (SetSecurityServiceOnStartSession). If the security service is not sent, then only tables/functions that are not password protected are available.

https://elstersolutionsopensource.github.io/C12Adapter/class_m_protocol_c12.html#ae4ba7c99bbbe38cb5ba6775b4f2bfe96

if you are using ANSI C12.21, you have the option of sending the security service or authentication service (SetEnableAuthentication). Most likely you want to send the authentication service. 

https://elstersolutionsopensource.github.io/C12Adapter/class_m_protocol_c1221.html#a9a891b54b82aed676b739f4d8f1ce990

Best Regards,
Nicole

**Comment by maufc** [comment]
Hi Nicole.
I am sorry I couldn't keep the secret for the password. I just edit my comment trying to keep it :)
You are completely right about the error. It was the security on start variable seted to false. 
I also could connect via TCP/IP following your explications. That would be the most important progress.
So I got almost all the tables. Nevertheless, at least one continues with a restriction. I presume it is for manufacturer or sensible information. 
There's a lot of information. Some understandable and some other not. 
There are tables without description, making it complicate to find an specific request. 
Do you know if this data is available before immerse into serial sniffing?
Going to serial raw data is like going backwards. That would be as going through a process already resolved by this library.
Any tip or recommendation in this point?
I just need the instant values of the meter. Those are the 'instrumentation' data.
Again, thank you very much for share your knowledge.
Best regards,

**Comment by Boumhicha** [comment]
Hi Nicole,
this topic is so helpful, can you please mention where can I find the PQM threshold values ?? I configure it by Metercat and I read the packets by serial monitoring but I didn't find the PQM values, can you please tell me where can I find it.

**Comment by ElsterSolutionsOpensource** [comment]
I can't advise on data structures. I can only point you to the ANSI C12.19 standard. The C12Adapter library only handles the communications to the device, it does not provide support for the interpretation of that data.
